/**
 * Builds the default dock arrangement declaratively from the panel registry.
 *
 * This is imperative-by-necessity: dockview's `addPanel` positions each panel
 * relative to an already-placed one, so order matters and the sequence below
 * encodes the §A.1 diagram directly.
 *
 * Doing it this way rather than shipping a hand-written `SerializedDockview`
 * blob matters: a serialized blob is opaque, breaks silently when dockview
 * changes its format, and would have to be regenerated by hand every time a
 * panel is added. Rebuilding from the registry means "Reset Layout to Default"
 * is always correct by construction.
 */

import type { DockviewApi } from 'dockview-react';

import type { PanelRegistry } from './panelRegistry';

export interface ApplyDefaultLayoutOptions {
  /** Width of the left dock in px. */
  leftWidth?: number;
  /** Width of the right dock in px. */
  rightWidth?: number;
  /** Height of the bottom (timeline) dock in px. */
  bottomHeight?: number;
  /** Height of the center-bottom (video monitor) region in px. */
  centerBottomHeight?: number;
}

const DEFAULTS = {
  leftWidth: 260,
  rightWidth: 300,
  bottomHeight: 140,
  centerBottomHeight: 260,
} as const;

/**
 * Clears the dock and lays out every `openByDefault` panel per the A.1 diagram.
 *
 * The build order is load-bearing:
 *   1. center-top first — it becomes the anchor everything else attaches to.
 *   2. center-bottom below it, so they share the center column.
 *   3. left / right as siblings of the center column.
 *   4. bottom-full last, so it spans the full width beneath all three columns.
 *
 * Adding the bottom panel earlier would make it a sibling of the center column
 * only, and it would not span the full width.
 */
export function applyDefaultLayout<Id extends string>(
  api: DockviewApi,
  registry: PanelRegistry<Id>,
  options: ApplyDefaultLayoutOptions = {},
): void {
  const { leftWidth, rightWidth, bottomHeight, centerBottomHeight } = {
    ...DEFAULTS,
    ...options,
  };

  api.clear();

  const open = (id: Id) => registry.require(id);
  const openable = (location: Parameters<PanelRegistry<Id>['byLocation']>[0]) =>
    registry.byLocation(location).filter((p) => p.openByDefault);

  // --- 1. center-top: the anchor. Usually the Viewport. ---
  const centerTop = openable('center-top');
  let anchorId: string | null = null;

  for (const descriptor of centerTop) {
    api.addPanel({
      id: descriptor.id,
      component: descriptor.id,
      title: descriptor.title,
      ...(anchorId
        ? { position: { referencePanel: anchorId, direction: 'within' as const } }
        : {}),
    });
    anchorId ??= descriptor.id;
  }

  // Nothing to anchor to means an empty registry; a bare dock is the right
  // outcome rather than a thrown error mid-layout.
  if (!anchorId) return;

  // --- 2. center-bottom: split below the anchor ---
  const centerBottom = openable('center-bottom');
  let centerBottomId: string | null = null;
  for (const descriptor of centerBottom) {
    api.addPanel({
      id: descriptor.id,
      component: descriptor.id,
      title: descriptor.title,
      initialHeight: descriptor.defaultSize ?? centerBottomHeight,
      position: centerBottomId
        ? { referencePanel: centerBottomId, direction: 'within' }
        : { referencePanel: anchorId, direction: 'below' },
    });
    centerBottomId ??= descriptor.id;
  }

  // --- 3. left and right docks, relative to the center column's top ---
  let leftId: string | null = null;
  for (const descriptor of openable('left')) {
    api.addPanel({
      id: descriptor.id,
      component: descriptor.id,
      title: descriptor.title,
      initialWidth: descriptor.defaultSize ?? leftWidth,
      position: leftId
        ? { referencePanel: leftId, direction: 'within' }
        : { referencePanel: anchorId, direction: 'left' },
    });
    leftId ??= descriptor.id;
  }

  let rightId: string | null = null;
  for (const descriptor of openable('right')) {
    api.addPanel({
      id: descriptor.id,
      component: descriptor.id,
      title: descriptor.title,
      initialWidth: descriptor.defaultSize ?? rightWidth,
      position: rightId
        ? { referencePanel: rightId, direction: 'within' }
        : { referencePanel: anchorId, direction: 'right' },
    });
    rightId ??= descriptor.id;
  }

  // --- 4. bottom-full: spans everything. Must be last. ---
  let bottomId: string | null = null;
  for (const descriptor of openable('bottom-full')) {
    api.addPanel({
      id: descriptor.id,
      component: descriptor.id,
      title: descriptor.title,
      initialHeight: descriptor.defaultSize ?? bottomHeight,
      position: bottomId
        ? { referencePanel: bottomId, direction: 'within' }
        : { referencePanel: anchorId, direction: 'below' },
    });
    bottomId ??= descriptor.id;
  }

  // Focus the anchor so keyboard users start somewhere sensible.
  api.getPanel(anchorId)?.focus();
  void open;
}

/**
 * Opens a single panel at its registered default location.
 *
 * Used by the Panels menu to reopen something the user closed. Falls back to
 * adding it to the active group when its natural neighbours are all gone,
 * because a panel that cannot be reopened is worse than one in the wrong place.
 */
export function openPanelAtDefaultLocation<Id extends string>(
  api: DockviewApi,
  registry: PanelRegistry<Id>,
  id: Id,
): void {
  const descriptor = registry.require(id);

  const existing = api.getPanel(id);
  if (existing) {
    existing.api.setActive();
    return;
  }

  // Find a still-open sibling to anchor against.
  const anchorFor: Record<string, { ref: Id[]; direction: 'left' | 'right' | 'below' | 'above' }> =
    {
      left: { ref: registry.byLocation('center-top').map((p) => p.id), direction: 'left' },
      right: { ref: registry.byLocation('center-top').map((p) => p.id), direction: 'right' },
      'center-bottom': {
        ref: registry.byLocation('center-top').map((p) => p.id),
        direction: 'below',
      },
      'center-top': {
        ref: registry.byLocation('center-bottom').map((p) => p.id),
        direction: 'above',
      },
      'bottom-full': {
        ref: registry.byLocation('center-top').map((p) => p.id),
        direction: 'below',
      },
    };

  if (descriptor.defaultLocation === 'float') {
    const panel = api.addPanel({
      id: descriptor.id,
      component: descriptor.id,
      title: descriptor.title,
      floating: { width: 420, height: 320, x: 80, y: 80 },
    });
    panel.api.setActive();
    return;
  }

  const plan = anchorFor[descriptor.defaultLocation];
  const reference = plan?.ref.map((refId) => api.getPanel(refId)).find(Boolean);

  api
    .addPanel({
      id: descriptor.id,
      component: descriptor.id,
      title: descriptor.title,
      ...(reference && plan
        ? { position: { referencePanel: reference.id, direction: plan.direction } }
        : {}),
    })
    .api.setActive();
}
